// revisa el codigo anterior con copilot
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Óptica en Terreno - Inicio</title>
    <link rel="stylesheet" href="css/estilos.css">
</head>
<body>
     <?php include 'generar_css.php'; ?>
    <?php include 'header.php'; ?>
    <?php include 'menu.php'; ?>
    <?php include 'redes.php'; ?>
   
    <main>
        <h2>Bienvenido ....... a nuestro Servicio de Salud y Óptica empresarial en Terreno.</h2>
        <h3>Nos acercamos a tu empresa para cuidar la salud visual y bienestar de tus colaboradores, brindando atención profesional y soluciones a su medida.</h3>
        

        <img src="imagenes/inicioservicios.png" alt="Servicios" style="max-width: 400px; border-radius: 10px;">
        <p></p>
    </main>

    <?php include 'footer.php'; ?>
</body>
</html>

 
