<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Óptica en Terreno - Inicio</title>
    <link rel="stylesheet" href="css/estilos.css">
</head>
<body>
    <?php include 'header.php'; ?>
    <?php include 'menu.php'; ?>

    <?php include 'redes.php'; ?>
    <main>
 
        <h4>Las empresas que han elegido nuestro servicios, su confianza es nuestra mejor carta de presentación.</h4>
        
        <img src="imagenes/PrincipalesClientes.png" alt="Servicios" style="max-width: 600px; border-radius: 10px;">
        <p></p>
    </main>

    <?php include 'footer.php'; ?>
</body>
</html>

